### PR TITLE
Add mutex protections and further refactor

### PR DESCRIPTION
**Pull request by ZachGarcia42**

### CODE REVIEW

**Comment by ZachGarcia42** [comment]
* **#107** <a href="https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/107?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ZachGarcia42 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by maxslarsson — APPROVED** [review]
Looks good to me! Out of curiosity did you run into an issue? Or is this just preventative?

**Comment by ZachGarcia42** [comment]
> Looks good to me! Out of curiosity did you run into an issue? Or is this just preventative?

Preventative based on my dad's review

**Comment by ZachGarcia42** [comment]
### Merge activity

* **Oct 7, 10:32 PM EDT**: @ZachGarcia42 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/107).

**Pull request merged**
