### PR TITLE
Add basic login auth

### LINKED ISSUE #41: Add NextAuth to backend

### PR DESCRIPTION
**Pull request by maxslarsson**
Fixes #41

### CODE REVIEW

**Comment by maxslarsson** [comment]
* **#82** <a href="https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/82?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @maxslarsson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ZachGarcia42 — CHANGES_REQUESTED** [review]
I'm getting a server error whenever I try to login:





This error should be handled more gracefully, and we should probably set trust host to true for now and create a ticket for updating that to be a configured url instead: https://authjs.dev/reference/nextjs#trusthost

**Comment by maxslarsson** [comment]
Yep, I set trustHost to true and it seems to be working now. I also forgot to add the encryption token for NextAuth (which is auto put into a .env.local file by running `npx auth secret`). If you test it now, it should work!

**Comment by maxslarsson** [comment]
### Merge activity

* **Oct 2, 12:09 PM EDT**: @maxslarsson started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/82).

**Comment by maxslarsson** [comment]
### Merge activity

* **Oct 2, 12:10 PM EDT**: @maxslarsson merged this pull request with [Graphite](https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/82).

**Pull request merged**
