### PR TITLE
Custom drag handle and fix to screen height

### PR DESCRIPTION
**Pull request by maxslarsson**

### CODE REVIEW

**Comment by maxslarsson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/78?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#78** <a href="https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/78?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#76** <a href="https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/76?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @maxslarsson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ZachGarcia42 — APPROVED** [review]
Custom drag handle looks good. Not sure what "fix to screen height" means, as I don't see any difference in tile sizing options

**Comment by maxslarsson** [comment]
Whoops it was a typo. Meant to say "fit" I think. Basically, it is no longer possible to drag a widget or resize a widget past the screen height. 

That being said, it is not perfect at all and I didn't even intend to implement this. It just came because of other tweaks I made. So if you make a widget have full screen height, and then drag another widget above that widget, forcing it down, then the widgets will extend past the end of the screen.

**Comment by maxslarsson** [comment]
### Merge activity

* **Sep 30, 8:59 PM EDT**: @maxslarsson started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/78).

**Pull request merged**
