### PR TITLE
Run code through Prettier

### PR DESCRIPTION
**Pull request by maxslarsson**

### CODE REVIEW

**Comment by maxslarsson** [comment]
* **#79** <a href="https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/79?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @maxslarsson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ZachGarcia42 — APPROVED** [review]
Is this something we should set up as a Github action?

**Comment by maxslarsson** [comment]
Might be worth having. Maybe let's discuss it tomorrow?

**Comment by maxslarsson** [comment]
### Merge activity

* **Oct 1, 12:15 PM EDT**: @maxslarsson started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/79).

**Pull request merged**
