### PR TITLE
Update the control page with prop/ elec advice

### PR DESCRIPTION
**Pull request by AlyNat75**

### CODE REVIEW

**Comment by AlyNat75** [comment]
* **#123** <a href="https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/123?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AlyNat75 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ZachGarcia42 — COMMENTED** [review]
LGTM

**Review by maxslarsson — APPROVED** [review]
Looks good to me! Thank you Aly

**Comment by AlyNat75** [comment]
### Merge activity

* **Oct 23, 7:15 PM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/123).

**Pull request merged**
