### PR TITLE
Build for both linux/amd64 and linux/arm64

### LINKED ISSUE #32: Build Docker for both amd64 and arm64

### PR DESCRIPTION
**Pull request by maxslarsson**
Fixes #32

### CODE REVIEW

**Comment by maxslarsson** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/30?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#30** <a href="https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/30?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#29** <a href="https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/29?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#24** <a href="https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/24?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @maxslarsson and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ZachGarcia42 — COMMENTED** [review]
Looks good to me. Want to see passing status checks, and can you try running the image on a raspi 4 and confirm it works there? Just leave a comment on this PR when that's confirmed (maybe a picture too?)

**Review by ZachGarcia42 — APPROVED** [review]
Ran on Pi 4 Successfully

**Comment by ZachGarcia42** [comment]
### Merge activity

* **Sep 21, 12:35 PM EDT**: @ZachGarcia42 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/30).

**Pull request merged**
